sudo: required
services:
  - docker
language: node_js
node_js: 10
cache:
  directories: node_modules
branches:
  only:
    - master
addons:
  ssh_known_hosts: '$HOST'
before_install:
  - openssl aes-256-cbc -K $encrypted_f98e8b1af11f_key -iv $encrypted_f98e8b1af11f_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
  - yarn install
script:
  - yarn run docs:build
  - docker build -t jolylai/notebook .
  - docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
  - docker push jolylai/notebook
deploy:
  provider: pages
  skip-cleanup: true
  github-token: '$GITHUB_TOKEN'
  keep-history: true
  local_dir: dist
  on:
    branch: master
after_deploy:
  - chmod 600 ~/.ssh/id_rsa
  - scp -o "StrictHostKeyChecking no" -i id_rsa docker-compose.yml root@$HOST:/root/
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$HOST "cd /root/;docker-compose -f docker-compose.yml pull;docker-compose -f docker-compose.yml up -d;exit"
