language: node_js
node_js: 10
sudo: required
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5fcb8b10af91_key -iv $encrypted_5fcb8b10af91_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
  - yarn install
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
after_success:
  - chmod 600 ~/.ssh/id_rsa
  - scp -o stricthostkeychecking=no -r docs/.vuepress/dist root@106.12.140.131:/var/www/html
