language: node_js
node_js: 10
sudo: required
cache:
  directories: node_modules
branches:
  only:
    - master
script:
  - yarn install
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: '$GITHUB_TOKEN'
  keep-history: true
  local_dir: dist
  on:
    branch: master
