language: node_js
node_js: stable
sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5fcb8b10af91_key -iv $encrypted_5fcb8b10af91_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
  - yarn install
script:
  - yarn run docs:build
  - docker build -t notebook .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push jolylai/notebook
  on:
    branch: master
after_script:
  - docker images
