language: node_js
node_js: stable
install:
  - yarn
script:
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
