language: node_js
node_js: stable
branches:
  only:
  - master
install:
- yarn install
script:
- yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_5fcb8b10af91_key -iv $encrypted_5fcb8b10af91_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
